services:
  - type: web
    name: portfolio-client
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 20.18.3
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: VITE_API_URL
        sync: false
      - key: NODE_ENV
        value: production
    staticPublishPath: ./dist
